// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZMB51jjA2ylQM_JKSIQHh6yJxXibDUc',
    appId: '1:715961730893:web:dfa6cfa014b085fdfa5904',
    messagingSenderId: '715961730893',
    projectId: 'flutter-todo-a7fa3',
    authDomain: 'flutter-todo-a7fa3.firebaseapp.com',
    storageBucket: 'flutter-todo-a7fa3.firebasestorage.app',
    measurementId: 'G-TZP62K41XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiau9_UtDyf61PMH01xRPHxC1Ri-hXopE',
    appId: '1:715961730893:android:43f54215ed466268fa5904',
    messagingSenderId: '715961730893',
    projectId: 'flutter-todo-a7fa3',
    storageBucket: 'flutter-todo-a7fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWv-SaYhEjd0sa0LXGVjCkxT237m8JKUQ',
    appId: '1:715961730893:ios:f61dfd34a51a04a6fa5904',
    messagingSenderId: '715961730893',
    projectId: 'flutter-todo-a7fa3',
    storageBucket: 'flutter-todo-a7fa3.firebasestorage.app',
    iosBundleId: 'com.krindale.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWv-SaYhEjd0sa0LXGVjCkxT237m8JKUQ',
    appId: '1:715961730893:ios:48e87e1d663fb5a1fa5904',
    messagingSenderId: '715961730893',
    projectId: 'flutter-todo-a7fa3',
    storageBucket: 'flutter-todo-a7fa3.firebasestorage.app',
    iosBundleId: 'com.example.todoBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUZMB51jjA2ylQM_JKSIQHh6yJxXibDUc',
    appId: '1:715961730893:web:40f30d7ba3adabd1fa5904',
    messagingSenderId: '715961730893',
    projectId: 'flutter-todo-a7fa3',
    authDomain: 'flutter-todo-a7fa3.firebaseapp.com',
    storageBucket: 'flutter-todo-a7fa3.firebasestorage.app',
    measurementId: 'G-E32FCXTDK6',
  );
}
